### ISSUE TITLE
Seeing deprecation warning for ember data 1.13.4

### ISSUE THREAD

**Issue by basz** [201-created/ember-data-hal-9000#17]
Your custom serializer uses the old version of the Serializer API, with `extract` hooks. Please upgrade your serializers to the new Serializer API using `normalizeResponse` hooks instead.

more info : https://github.com/emberjs/data/blob/v1.13/packages/ember-data/lib/system/serializer.js#L28

**Comment by bantic** [comment]
@basz Thanks for finding this. I'm going to look into upgrading the hal adapter to work with latest ember data.

**Comment by basz** [comment]
Appreciated!

**Comment by leninayya** [comment]
@basz 
How to use HAL-9000 without ember-cli?

**Comment by basz** [comment]
@leninayya I honestly have no idea... Not sure ember-data-hal-9000 has been designed for such a use-case.

**Comment by bantic** [comment]
@leninayya This is an ember-cli addon, there is no built "globals mode" script of it that you would use without ember-cli.  However, you can use [ember-giftwrap](https://github.com/ef4/ember-giftwrap) to package it up for a global mode app, I'd suggest giving that a try.

**Comment by leninayya** [comment]
Thank You @basz  @bantic

**Comment by bantic** [comment]
@basz version `0.3.0-beta.2` has support for ember data 1.13.4 and beyond. If you could try installing it and give any feedback that would be very helpful. thanks! (see #25 and #24 for more)

**Comment by bantic** [comment]
@basz now that there is a version of ember-data-hal-9000 (0.3.x) that supports ember-data 1.13+, this should be fixed. I'll close now, but please reopen if I'm wrong.
