### ISSUE TITLE
Support of ember-cli install and loading

### ISSUE THREAD

**Issue by clawfire** [201-created/ember-data-hal-9000#21]
It will be really great to see a support of [ember-cli](http://ember-cli.com) for this :)

**Comment by mixonic** [comment]
@clawfire can you clarify? This project is an add-on for ember-cli.

**Comment by bantic** [comment]
Perhaps the issues is to support newer ember-data without deprecation warnings? I'll close this as I think the addon-ness of the project is established. :) Please reopen if I misunderstood!

**Comment by clawfire** [comment]
@bantic yeah you're right. that was my point. Also maybe updating the documentation to use the `ember install` instead of `npm install` to clear all possible misunderstood for newbies :D
