### ISSUE TITLE
New HAL9k explicitly does not accept 'attributes' as a key.

### ISSUE THREAD

**Issue by gentlefox** [201-created/ember-data-hal-9000#30]
In the wonderful world of Back-end provides data, and you're left to work with it, I have a large Ember project where most models have a related model called attribute. Being a hasMany relationship, alas results in a relational key called "attributes".

With the older version of this addon, there were almost no issues - and the ones that existed was solely from back-end data and their habit of regularly using reserved words as model / object / key names.

While Ember did require 2 differently structured calls in order to differentiate where you were getting the attributes of the model or the relational models, it still worked easily. Now with your latest release of this addon, "attributes" is now a reserved word. While agreed, not the best name to use, it isn't set as reserved by either Ember or JSON-API.

Is this likely to stay this way?

Curious to know, before I reconstruct the site replacing all instances of the term "attribute" and splice in a data.key change to and from the server, else doctor the addon.

Thanks.

**Comment by bantic** [comment]
@gentlefox Thanks — I think you're right, this is overly restrictive on the part of the adapter. There shouldn't be a problem on ember's or the adapter's side to have an attribute called `attributes`.

For my reference, here's the offending assertion:
https://github.com/201-created/ember-data-hal-9000/blob/master/addon/serializer.js#L186-L187

@makepanic Any reason that `attributes` is explicitly disallowed like this?

**Comment by makepanic** [comment]
I think the `attributes` assertion came from the earliest steps of ember-data 1.13.8+ refactoring and was never removed.

As you said it shouldn't be there and everything works without the assertion.
I opened https://github.com/201-created/ember-data-hal-9000/pull/32 that removes it.

**Comment by bantic** [comment]
thanks!

**Comment by gentlefox** [comment]
I'm awestruck!
Comprehensive appreciation, and thanks for the amazing work providing this adapter.
Thank you.

**Comment by bantic** [comment]
@gentlefox thank *you* for the note! Much appreciated. cc @makepanic
