### ISSUE TITLE
Lack of id in some relationships throw error

### ISSUE THREAD

**Issue by jaydiablo** [201-created/ember-data-hal-9000#34]
I'm working on building an API using Zend's Apigility product, which exposes a HAL+JSON API.  One of the options you can specify for a particular resource or collection is the "max_depth", which will limit how many nested relationships are rendered in the response.

When this limit is hit, it'll still provide the name of the relationship, but the only data that exists inside that object is the _links element with the self link.  Here's an excerpt from the documentation:

>max_depth - integer; limit to what nesting level entities and collections are rendered; if the limit is reached, only self links will be rendered. default value is null, which means no limit: if unlimited circular references are detected, an exception will be thrown to avoid infinite loops.

https://github.com/zfcampus/zf-hal#key-metadata_map

So when this depth is reached, a resource may look something like this:

```
{
  "id":15,
  "slug":"slugify",
  "title":"Slugify-12",
  "_embedded":{
    "articles":[
      {
        "id":50,
        "slug":"article1",
        "title":"Article 1",
        "_embedded":{
          "users":[
            {
              "_links":{
                "self":{
                  "href":"http:\/\/localhost:8888\/users\/1"
                }
              }
            }
          ]
        },
        "_links":{
          "self":{
            "href":"http:\/\/localhost:8888\/articles\/50"
          }
        }
      }
    ]
  },
  "_links":{
    "self":{
      "href":"http:\/\/localhost:8888\/blogs\/15"
    }
  }
}
```

Notice that the embedded users object doesn't have any properties except for the _links proptery containing the self link.

When ember processes this response with the HAL 9000 serializer, it complains:

>Error: Assertion Failed: You must include an 'id' for user in an object passed to 'push'

I can silence some of these by modifying the serializer to ignore objects without an id property, but so far it still complains on some other requests.

As far as I know, the HAL spec doesn't require a resource to have an id (but it seems that Ember Data does).  Should HAL 9000 ignore resources without an id?  In my case, a later request to fetch the nested object would end up returning an id, it's just not available in this particular request since it's too deep.

Any thoughts? Advice?  I can continue to mess with the serializer to handle these cases better, as I feel that this is where the work should be focused (rather than in zf-hal), since the spec is so permissive.

**Comment by makepanic** [comment]
You're right the problem is that ember-data requires an id for each record. 
It's possible to overwrite the [id extraction](https://github.com/201-created/ember-data-hal-9000/blob/master/addon/serializer.js#L84).

I think the general problem is that jsonapi requires ids for included/embedded records http://jsonapi.org/format/#document-compound-documents. It needs them to map the `included` records to another records relationship.

Afaik you could work around this limitation by not embedding the > `max_depth` records and simply link them.

**Comment by mixonic** [comment]
It may be theoretically possible to make your API response work, but it would be very expensive to render those users. To render a list of those users, you would need to make an API call for each one individually.

HAL is very permissive, and is probably too permissive to be consumed by modeling API consumer without some concessions. I don't believe it would be trivial to generally support the case your looking to see supported @jaydiablo.

You could override the id extraction as @makepanic suggested, and fetch it out of the `self` URL.

**Comment by bantic** [comment]
@jaydiablo HAL treats a `self` link as an id, so it makes sense to me that your API considers that a minimum viable payload for those embedded resources. IMO it may make sense to conflate the `id` property and the `self` url in this HAL adapter, but it raises some other problems related to how Ember Data generates the urls it uses to fetch data.

I am also +1 on overriding the id extraction to regex it out of that self link url.

**Comment by jaydiablo** [comment]
Thanks for the replies.  I am overwriting the id extraction to pull the id out of the self URL at the moment, and that seems to work pretty well for this use case.  The relationships that it loads in this manner are fetched asynchronously later in the app if needed to display the object's attributes.  If I put the depth deep enough (I can't remove it completely, as it can result in recursion) Ember shouldn't have to do much individual fetching, but I'll keep an eye on it.
